# -*- coding: utf-8 -*-
"""imgs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m03gz2kFDzxjdlT1kn1uaUrPBhFcGnvS
"""

import json
import os

with open('./export.json') as f:
  data = json.load(f)

import urllib.request

# If Original FOlder doesn't exist, create it, else delete all files in it
if not os.path.exists('./data/Original_Images'):
    os.makedirs('./data/Original_Images')
else:
    for file in os.listdir('./data/Original_Images'):
        os.remove('./data/Original_Images/'+file)

# If Mask Folder doesn't exist, create it, else delete all files in it
if not os.path.exists('./data/Original_Masks'):
    os.makedirs('./data/Original_Masks')
else:
    for file in os.listdir('./data/Original_Masks'):
        os.remove('./data/Original_Masks/'+file)

def saveImages(json):
    for data in json:
        orgImgName = data['External ID']
        print()
        print("Downloading: " + orgImgName)

        try:
            if len(data['Label']['objects']) > 0 and data['Label']['objects'][0].get('instanceURI'):
                if len(data['Reviews']) < 1 or (len(data['Reviews']) > 0 and data[0]['Reviews'][0]["score"] != -1):
                    maskImgName = data['External ID'].split(".")[0] + '.PNG'
                    urllib.request.urlretrieve(data['Labeled Data'], 'data/Original_Images/'+orgImgName)
                    # urllib.request.urlretrieve(data['Label']['objects'][0]['instanceURI'], 'Mask/'+orgImgName)
                    
                    urllib.request.urlretrieve(data['Label']['objects'][0]['instanceURI'], 'data/Original_Masks/'+maskImgName)
                else:
                    print("Skipping " + orgImgName + " because it is not reviewed or it is rejected")
            else:
                print("No mask or URL found for " + orgImgName)
        except KeyError:
            print(orgImgName + " not applicable")

saveImages(data)

